
name: Comment Latest Version In PR
on:
  pull_request:
    types: [opened, reopened]
  workflow_call:

jobs:
  comment_latest_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Get Versions From DockerHub
        id: get_versions # su for skopeo in ubuntu
        run: |
          sudo skopeo login --username bieldatalab --password ${{ secrets.DOCKERHUB_READ_ACCESS_TOKEN }} registry.hub.docker.com
          JSON_RESULT=$(sudo skopeo list-tags docker://registry.hub.docker.com/bieldatalab/${{ github.event.repository.name }})
          JSON_RES=$(echo "$JSON_RESULT" | tr -d '\n' | sed s/[[:space:]]//g)
          echo "::set-output name=json_result::$JSON_RES"
      - name: Extract And Comment Latest Version
        run: |
          echo $SKOPEO_RES skopeo_res
          echo $PR_NUMBER pr_number
          pip install PyGithub cryptography
          python3 -m app.github_app_comment_script -r $REPO -p $PR_NUMBER -a $APPS_ID
        env:
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SKOPEO_RES: ${{ steps.get_versions.outputs.json_result }}
          REFRESH_TAG_PEM: "${{ secrets.REFRESH_TAG_PEM }}"
          APPS_ID: 181614
          REP_OWNER_NAME: "BIEL-Datalab"


