name: Push tag pipeline
on:
  workflow_call:
    inputs:
      deployment_yaml_path:
        description: "deployment.yaml path"
        default: 'deployment/deployment.yaml'
        required: false
        type: string

jobs:
  push_tag:
    if: ${{ contains(toJSON(github.event.commits), 'Update image tag to') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Extract Version
        id: lookupVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.spec.template.spec.containers[0].image' ${{ inputs.deployment_yaml_path }}
      - name: Push Tag
        run: |
          git tag $(echo "${{ steps.lookupVersion.outputs.result }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          git push --tag