name: Push tag pipeline
on:
  workflow_call:

jobs:
  push_tag:
    if: ${{ contains(toJSON(github.event.commits), 'Update image tag to') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Extract Version
        id: lookupVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.spec.template.spec.containers[0].image' 'deployment/deployment.yaml'
      - name: Push Tag
        run: |
          git tag $(echo "${{ steps.lookupVersion.outputs.result }}"  | sed "s/.*release-\([^ ]*\).*$/\1/")
          git push --tag
