name: Update helm application version pipeline
on:
  workflow_call:
    inputs:
      value_yaml_path:
        description: "values.yaml path"
        default: 'chart/testing/values.yaml'
        required: false
        type: string

jobs:
  update_release_version:
    if: ${{ github.event.review.state == 'approved' && contains(github.event.review.body, 'release-') && (github.event.pull_request.base.ref != 'master' || github.event.pull_request.head.ref != 'test')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - name: Extract Version
        id: image
        run: |
          VERSION=release-$(echo "${{ github.event.review.body }}" | tr -d '\n' | sed "s/.*release-\([^ ]*\).*$/\1/")
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - name: Modify Chart Yaml Tag
        uses: mikefarah/yq@master
        with:
          cmd:
            yq eval -i '.image.tag="${{ steps.image.outputs.version }}"' ${{ inputs.value_yaml_path }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: datalab-devops
          author_email: datalab@bielcrystal.com
          message: "Update image tag to ${{ steps.image.outputs.version }}"
          add: "*.yaml"
